services:
  - type: web
    name: mcp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mcp-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://mcp-backend.onrender.com/oauth2-redirect
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

databases:
  - name: mcp-db
    databaseName: mcp
    user: mcp
    plan: free 